### ISSUE TITLE
Link to extras after the workshop?

### ISSUE THREAD

**Issue by bsmith89** [bsmith89/2016-04-29-ucsf#15]
Does anyone else have documents they would like to link to on the course website?

I was going to archive the etherpads and upload that HTML.  Maybe Jupyter Notebooks would be a useful addition.

I also know Becca said she would share some "additional reading" with our learners.

**Comment by dotsdl** [comment]
I'll have something by mid-week (hopefully). I'm going to merge my [cheat-sheet notebook](http://nbviewer.jupyter.org/gist/dotsdl/c0aac21f0d143dc73a9e20d974e7f8f1) and my [live notebook](https://github.com/dotsdl/swc_ucsf_python/blob/master/Mosquito%20Analysis.ipynb) with standalone commentary on what was done. I'll post the link here once it's somewhere.

**Comment by rdtarvin** [comment]
I put the links on the etherpad but this is it: http://ccbbatut.github.io/Biocomputing_Spring2016/resources/

My notebooks:

Day 1: https://github.com/rdtarvin/swc_UCSF_python/blob/master/RDT_notebook.ipynb
Day 2: https://github.com/rdtarvin/swc_UCSF_python/blob/master/SWC_Day2_notebook.ipynb

**Comment by bsmith89** [comment]
I've archived the two etherpads and swapped out the link to them on the workshop site. (dbfcad9)

Maybe this was a bad idea, since we might want to post our resources directly to the etherpad?

Thoughts?

**Comment by rdtarvin** [comment]
Looks fine to me. Paste in the resources before archiving?

**Comment by dotsdl** [comment]
Resolving my notebooks today. Should have the full lesson hosted by tonight.

**Comment by bsmith89** [comment]
I'll re-archive the notebooks and update the site once everyone gives me the OKAY.

**Comment by dotsdl** [comment]
Thanks @bsmith89. Apologies for being the slow horse here; day job's been keeping me busy. Will have this closed up this weekend by hook or by crook.

**Comment by dotsdl** [comment]
@bsmith89 finally done; the full repo giving the complete lesson I taught at the workshop is now up: https://github.com/dotsdl/swc_intermediate_python

The notebook can also be viewed on nbviewer: http://nbviewer.jupyter.org/github/dotsdl/swc_intermediate_python/blob/master/intermediate_scientific_python.ipynb

**Comment by bsmith89** [comment]
~~Please add your links to the room's etherpad.  @fu9ar, did you have anything to add?~~

Edit: n.m., I'll just follow the format from our room's pad.

**Comment by bsmith89** [comment]
Resolved by 1e202e601ba0ff5a479979776acb229830057d00.

**Comment by kevin-vilbig** [comment]
I wanted to note that I think I shared everything that I wanted to share in the etherpad.
