### ISSUE TITLE
The schedule on the website is inaccurate.

### ISSUE THREAD

**Issue by bsmith89** [bsmith89/2016-04-29-ucsf#7]

**Comment by dotsdl** [comment]
So, with regard to the schedule, what do we want to do? I have one proposal. The split would be according to which Python lesson gets taught in each room. There's the [Python Novice](https://github.com/swcarpentry/python-novice-inflammation) lesson, and the [Python Intermediate](https://github.com/swcarpentry/python-intermediate-mosquitoes/pull/11) lesson:

## Day 1

### Room 1
- Unix shell
- Python Novice

### Room 2
- Unix shell
- Python Intermediate

## Day 2

### Room 1
- Python Novice cont.
- Git

### Room 2
- Python Intermediate cont.
- Git

**Comment by bsmith89** [comment]
@fu9ar, @arieldeardorff, @ Becca Tarvin (Anyone have Becca's username?).

**Comment by bsmith89** [comment]
Is there any interest in teaching lessons besides Python, Git, and Shell?  (E.g. SQL, Make, etc.)

**Comment by kevin-vilbig** [comment]
I've found make to be useful, but I think this plan will be the most useful to the most people.
